name: Package and release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  curseforge_release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and release (CurseForge Release)
        uses: BigWigsMods/packager@v2

  curseforge_alpha:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and upload (CurseForge Alpha smoke test)
        uses: BigWigsMods/packager@v2
